apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: springboot-service-prometheus-monitor
  name: springboot-service-prometheus-monitor
  namespace: springboot-prometheus
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    scheme: http
  selector:
    matchLabels:
      app: springboot-prometheus